# permissions for end users to view machinesetmanageds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinesetmanaged-viewer-role
rules:
- apiGroups:
  - infrascheduler.bward.dev
  resources:
  - machinesetmanageds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrascheduler.bward.dev
  resources:
  - machinesetmanageds/status
  verbs:
  - get
