# permissions for end users to edit machinesetmanageds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinesetmanaged-editor-role
rules:
- apiGroups:
  - bward.dev.bward.dev
  resources:
  - machinesetmanageds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bward.dev.bward.dev
  resources:
  - machinesetmanageds/status
  verbs:
  - get
